# Generated by Django 5.0.6 on 2024-06-11 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=255)),
                ('adoption', models.CharField(max_length=255)),
                ('reimbursement', models.CharField(max_length=255)),
                ('csection', models.CharField(max_length=255)),
            ],
        ),
    ]
