# Generated by Django 5.0.6 on 2024-06-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babybytes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
