# Generated by Django 5.0.6 on 2024-06-11 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babybytes', '0003_remove_messages_id_alter_messages_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown', max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('adoption', models.CharField(max_length=255)),
                ('reimbursement', models.CharField(max_length=255)),
                ('csection', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
